
language: node_js
sudo: false
node_js:
  - "8.11.1"

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run codecov

deploy:
  provider: npm
  email: matti@vanils.fi
  api_key: $NPM_TOKEN
  on:
    tags: true