
language: node_js
dist: trusty
sudo: false
node_js:
  - "8.11.1"

addons:
  sonarcloud:
    organization: "vanils-github"
    token:
      secure: 4da4650dd7602842969c1c52aceee7a62f028858

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run codecov
  - sonar-scanner